spring:
  datasource:
    # URL de conexión a PostgreSQL:
    # jdbc:postgresql://<host>:<puerto>/<nombre_bd>
    # En desarrollo local suele ser localhost:5432 con la BD flota_dev
    url: jdbc:postgresql://localhost:5432/flota_dev
    driver-class-name: org.postgresql.Driver
    username: dev_user
    password: dev_pass
    #Para H2
    #url: jdbc:h2:mem:flota;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #driverClassName: org.h2.Driver
    #username: a
    #password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console


